name: PR

on:
  pull_request:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  REGISTRY: ghcr.io
  BASE_IMAGE_NAME: docker-test-base
  BASE_IMAGE_CACHE_TAG: ghcr.io/mnonnenmacher/docker-test-base:cache
  IMAGE_NAME: docker-test
  IMAGE_TAG: ghcr.io/mnonnenmacher/docker-test:latest

jobs:
  pr:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker base image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: docker-test-base:latest
          cache-from: type=registry,ref=${{ env.BASE_IMAGE_CACHE_TAG }}
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
      - name: Build App
        run: ./gradlew jibDockerBuild --image ${{ env.IMAGE_TAG }} -Djib.console=plain
      - name: Verify image
        run: docker run --rm ${{ env.IMAGE_TAG }}
      - name: Run Tests
        run: |
          docker run \
            -v ${{ github.workspace }}:/workspace \
            -v /home/runner/.gradle:/root/.gradle \
            -w /workspace \
            --entrypoint=sh ${{ env.IMAGE_TAG }} \
            -c "./gradlew run"
